# Generated by Django 4.0 on 2021-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
